### PR TITLE
Update IdentityServerAuthenticationHandler.cs

### PR DESCRIPTION
**Pull request by lisberPontes**
116 - Add Catch, maintain the execution of the 'finally' block. Thus, avoiding throw; inside catch.

### CODE REVIEW

**Comment by lisberPontes** [comment]
Is everything ok within the PR?

Cheers,

**Comment by leastprivilege** [comment]
Two comments

* changing the line breaks was unnecessary. We don't do code style PRs
* re-reading it, are you saying that unhandled exceptions are note logged automatically or swalloed - and need to be logged manually?

**Comment by lisberPontes** [comment]
> Two comments
> 
> * changing the line breaks was unnecessary. We don't do code style PRs
> * re-reading it, are you saying that unhandled exceptions are note logged automatically or swalloed - and need to be logged manually?

Hi,
The line breaks were added automatically by Resharper (sorry, I hope this doesn't bother you).
In relation to the second question, YES, that's exactly what happened to me, I've got a typo in my IDS and I wasn't getting any exception nor error logged. After adding this log I was able to see the exception and fixed it. So it is indeed something that should be added.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
